config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "flats#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
#
class FlatsController < ApplicationController
  def index
    if params[:query].present?
      @query = params[:query]
      @flats = Flat.where("name iLike '%#{params[:query]}%'")
    else
      @flats = Flat.all
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :number_of_guests, :price_per_night, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">

  <h1>Create a flat</h1>
  <hr>
  <%= simple_form_for(@flat) do |f| %>
    <%=  f.input :name %>
    <%=  f.input :address %>
    <%=  f.input :description %>
    <%=  f.input :number_of_guests %>
    <%=  f.input :price_per_night %>
    <%=  f.submit class: 'btn btn-primary'%>
    <%= link_to 'Cancel', '#', class: 'btn btn-danger ml-2' %>

  <% end %>
  <hr>

  <%= link_to "< Back to list", flats_path %>

</div>

app/views/flats/index.hmtl.erb
<div class="container">

  <h1>All flats</h1>
  <hr>
  <ul>
      <% @flats.each do |flat| %>
    <li>
      <%= link_to flat.name, flat_path(flat) %>
    </li>
    <% end %>
  </ul>
<hr>
<!--   <div class="btn btn-md">
    <span class="glyphicon glyphicon-plus"></span>
    <%= link_to "Add a new flat...", new_flat_path(@flat) %>
  </div> -->

</div>

app/views/flats/index.html.erb
<div class="container">

  <h1>All flats</h1>
  <hr>
  <div class="container">
    <div class="row">
      <% @flats.each do |flat| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://picsum.photos/200/300/?random');">
          <div class="card-category">
            <%= flat.price_per_night %> €
          </div>
          <div class="card-description">
            <h2><%= flat.name %></h2>
            <p>
              <%= flat.description %>
            </p>
            <p>Guests : <%= flat.number_of_guests %></p>
          </div>
          <div class="card-link">
          <%= link_to "More info", flat_path(flat) %>
          | <%= link_to "Edit", edit_flat_path(flat), class: "ml-3 text-warning" %>
          | <%= link_to "Remove", flat_path(flat), method: :delete, data: {confirm: "Are you sure?"}, class: "ml-3 text-danger" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">

  <h1>Create a flat</h1>
  <hr>
  <%= simple_form_for(@flat) do |f| %>
    <%=  f.input :name %>
    <%=  f.input :address %>
    <%=  f.input :description %>
    <%=  f.input :number_of_guests %>
    <%=  f.input :price_per_night %>
    <%=  f.submit class: 'btn btn-primary'%>
    <%= link_to 'Cancel', '#', class: 'btn btn-danger ml-2' %>

  <% end %>
  <hr>

  <%= link_to "< Back to list", flats_path %>

</div>

app/views/flats/show.html.erb
<div class="container">

        <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2))">
          <div class="card-category">
            <%= @flat.price_per_night %> €
          </div>
          <div class="card-description">
            <h2><%= @flat.name %></h2>
            <p>
              <%= @flat.description %>
            </p>
            <p>Guests : <%= @flat.number_of_guests %></p>
          </div>
        </div>
  <hr>

  <%= link_to "< Back to list", flats_path %>

</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  Simple Airbnb
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto flex">
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            <a class="list-inline btn btn-outline-primary my-2 my-sm-0 ml-2" href="/flats/new">Add Flat</a>
          </form>
        </div>
      </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/flats/new">Add Flat</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" integrity="sha384-PmY9l28YgO4JwMKbTvgaS7XNZJ30MK9FAZjjzXtlqyZCqBY6X6bXIkM++IkyinN+" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>